### ISSUE TITLE
Crates.io Questdb name

### ISSUE THREAD

**Issue by solanav** [questdb/c-questdb-client#26]
Hi! I'm the current owner of [crates.io/crates/questdb](https://crates.io/crates/questdb). If you'd like me to transfer it to you, I'll gladly do it.

**Comment by amunra** [comment]
@solanav Hi Solanav,
We've since settled on the `questdb-rs` crate name.. that said I may want to merge all the functionality into a single crate. Whilst this is an aspiration this is not currently in the pipeline.
I currently lack the time to merge the two code bases, that said, the code I have currently exists in `questdb::ingress` with the hope of adding more functionality in the future. The query code you have could, for example, be moved into `questdb::query`. I'd then enable-disable `ingress` and `query` selectively based on features. This would be a breaking change for existing users of the `questdb` crate, but it would be a trivial change to upgrade existing client code. There's also an opportunity to use it as a base for query functionality in the Python client, but that would be longer term.
If you want to go ahead and give me access to the `questdb` crate I'd very much welcome it - I'm just clear about what the expectations would be.

**Comment by solanav** [comment]
Sure! I'll give you access to the crate, I didn't mean to imply I wanted to merge. I don't consider the code I wrote of any value, just wanted to give y'all the name. Just give me a username and I'll give ownership on crates.io

**Comment by amunra** [comment]
This would be me: `amunra`
https://crates.io/users/amunra

Thank you!

**Comment by solanav** [comment]
Done! Good luck with the development of QuestDB and its libraries!

**Comment by amunra** [comment]
Thank you!
